### PR TITLE
Ecto sql update

### LINKED ISSUE #95: ecto_sql 3.6 support
ecto_sql version 3.6 seems to break the adapter as some of the interface has been changed around.

### PR DESCRIPTION
**Pull request by darrenklein**
Closes #95

### CODE REVIEW

**Comment by darrenklein** [comment]
I guess this'll have to qualify as a major version release, no? Since it won't support < ecto_sql 3.6, etc.?

**Comment by bernardd** [comment]
So I looked at this last week - you could (I think) pretty easily continue to support older versions by including both variants of the function. The catch is that you'll get warnings about your @impl tags - I'm not sure I have an elegant way to fix that.

**Comment by bernardd** [comment]
Having said that, even if you don't do that, I'm not sure whether requiring a new version of a dep is sufficient grounds for a new major release (especially when the dep itself has only gone up by a point release version). You're not breaking any public-facing APIs, only requiring the user to update their deps.

**Comment by darrenklein** [comment]
@bernardd Yeah, I considered maintaining backwards compatibility, but as you noted, you get the warnings. Are avoiding warnings a sufficient reason to not support backwards compatibility, or is it acceptable to allow warnings in such cases?

Anyway, regarding versioning, that's cool. Just a patch then?

**Comment by bernardd** [comment]
Well, if you want to take a lead from Ecto itself, it generates an unavoidable warning in order to maintain backwards compatibility with some older Elixir versions :) Having said that, I don't really think it's a huge deal - the number of people actually using the adapter is probably not huge, and a choice between sticking with a reasonable stable version, or updating ecto_sql is not a terrible one.

**Comment by darrenklein** [comment]
Ok - interesting about Ecto, but not clear which way you're advising, though. Maintain backwards compatibility, or force the ecto_sql update?

**Comment by bernardd** [comment]
Haha - I was deliberately avoiding explicitly "advising" anything :) I think on balance I'd just drop backwards compatibility. More trouble than it's worth.

**Comment by darrenklein** [comment]
Ha, then I guess I got exactly the answer you were looking to provide. I'm in agreement, I say drop the backwards compatibility. If people love ecto_sql 3.5 so much, they can marry it. In that case, this is ready for review (and merge, if approved).

**Comment by bernardd** [comment]
Looks good to me

**Pull request merged**
