### PR TITLE
support Ecto Query select tuples, like select: {record.field_1, recor…

### PR DESCRIPTION
**Pull request by alhambra1**
…d.field_2, ...}

### CODE REVIEW

**Comment by alhambra1** [comment]
I forgot we already support this in list form. I guess being able to use tuples doesn't hurt?

**Comment by bernardd** [comment]
Is there a test case to cover this?

**Comment by alhambra1** [comment]
Ah, good point. Let me see about that.

**Comment by alhambra1** [comment]
@bernardd I added a test for it.

**Comment by bernardd** [comment]
Perfect.

**Pull request merged**
