### PR TITLE
handle nil values in dynamodbset isEqual

### PR DESCRIPTION
**Pull request by alhambra1**

### CODE REVIEW

**Comment by bernardd** [comment]
Looks good - the CI is failing, though, because it needs `mix format` running over it.

**Comment by alhambra1** [comment]
Why is that something we need to do manually?

**Comment by alhambra1** [comment]
> Looks good - the CI is failing, though, because it needs `mix format` running over it.

If it's something that needs to be done for CI to pass, why not make it an automatic part of CI?

**Comment by alhambra1** [comment]
I'm not partial to running mix format on public facing code I wrote. But it's fine with me if someone else want to run mix format on it and commit.

**Comment by alhambra1** [comment]
CI passed now.

**Pull request merged**
