### PR TITLE
support ecto sources option for query results

### PR DESCRIPTION
**Pull request by AlexKovalevych**
https://github.com/circles-learning-labs/ecto_adapters_dynamodb/issues/2

### CODE REVIEW

**Comment by alhambra1** [comment]
This looks good to me. Can I ask, though, why did you add a `case` (line 246) for either `%{"Item" => item}` or `item`? And why does the `item` case not require processing of the "sourced" fields?

**Comment by AlexKovalevych** [comment]
@alhambra1 
`Dynamo.decode_item` supports multiple cases: `%{"Item" => item}` and just `item`, so i wasnt sure that `result` will always be a `%{"Item" => item}`. 
But i guess, that `case` is not needed, since `result = %{"Item" => item}` ? 
If so, i'll get rid of `case`.

**Comment by alhambra1** [comment]
Reviewing DynamoDB's docs, unless I'm missing something, it seems to me we'd always get a key, "Item" (get_item), "Items" (query) or "Responses" (batch_get_item). I think the `item` branch of the `case` statement is more of an Ex_Aws internal thing.

**Comment by AlexKovalevych** [comment]
> But if there is such a case, why wouldn't you want the "sourced" fields addressed there as well?
I missed it. Anyway, dropped the `case` statement, doesn't look like it ever hits the second branch of it (tests passed, except eqc, which i can't run).

**Comment by alhambra1** [comment]
Cool. The test-suite is not exhaustive but it's a good indicator nonetheless. Just waiting on an additional reviewer to see about merging. Thank you very much for contributing!

**Comment by nickelization** [comment]
Looks good to me, thanks!

**Pull request merged**
