### PR TITLE
Revert "Revert "47""

### PR DESCRIPTION
**Pull request by bernardd**
Re-PRing branch `47` after I prematurely merged it. See https://github.com/circles-learning-labs/ecto_adapters_dynamodb/pull/50

### CODE REVIEW

**Comment by darrenklein** [comment]
@alhambra1 I benchmarked the two approaches to this - `post_filter` uses `batch-get-item` and then I applied an `Enum.filter` to the results; `query` uses a query with a filter condition - I think these results speak for themselves:

```
Name                  ips        average  deviation         median         99th %
post_filter          8.33        0.120 s     ±4.95%        0.121 s        0.141 s
query               0.182         5.50 s     ±0.00%         5.50 s         5.50 s
```

I'm going to close this PR and revisit this with an eye toward post-filtering in cases where a filter condition has been applied.

**Comment by alhambra1** [comment]
What am I looking at? Can you please explain the headers? Not sure what the
acronyms or words mean.

**Comment by alhambra1** [comment]
Never mind, I found an explanation on Benchee.

**Comment by darrenklein** [comment]
For context, this was against our alpha DDB instance, circle table - there were 134 such records, 20 were filtered.

**Pull request closed without merging**
